# Generated by Django 5.2.3 on 2025-06-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('descricao', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('matricula', models.CharField(blank=True, default='', max_length=100)),
                ('senha', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoUsuarioPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelPermissao', models.IntegerField(choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Baixo')])),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.painel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.usuario')),
            ],
        ),
    ]
