# Generated by Django 5.2.3 on 2025-07-02 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompromissos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.IntegerField(blank=True, null=True)),
                ('identificador', models.CharField(blank=True, max_length=10, null=True)),
                ('compromisso', models.TextField(blank=True, max_length=10, null=True)),
                ('eixo', models.CharField(blank=True, max_length=100, null=True)),
                ('areaPanoGoverno', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('orgao', models.CharField(blank=True, max_length=50, null=True)),
                ('participa', models.CharField(blank=True, max_length=100, null=True)),
                ('g1', models.CharField(blank=True, max_length=10, null=True)),
                ('natureza', models.CharField(blank=True, max_length=50, null=True)),
                ('cem_dias', models.CharField(blank=True, max_length=50, null=True)),
                ('duzentos_dias', models.CharField(blank=True, max_length=10, null=True)),
                ('trezentos_dias', models.CharField(blank=True, max_length=10, null=True)),
                ('seisentos_dias', models.CharField(blank=True, max_length=10, null=True)),
                ('setecentos_trinta_dias', models.CharField(blank=True, max_length=10, null=True)),
                ('previsao_final', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('descricao', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoUsuarioPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelPermissao', models.IntegerField(choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Baixo')])),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.painel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
