# Generated by Django 5.2.3 on 2025-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompromissos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.IntegerField()),
                ('identificador', models.CharField(max_length=10)),
                ('compromisso', models.TextField(max_length=10)),
                ('eixo', models.CharField(max_length=50)),
                ('areaPanoGoverno', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=25)),
                ('orgao', models.CharField(max_length=15)),
                ('participa', models.CharField(max_length=50)),
                ('g1', models.CharField(max_length=5)),
                ('natureza', models.CharField(max_length=15)),
                ('cem_dias', models.CharField(max_length=15)),
                ('duzentos_dias', models.CharField(max_length=5)),
                ('trezentos_dias', models.CharField(max_length=5)),
                ('seisentos_dias', models.CharField(max_length=5)),
                ('setecentos_trinta_dias', models.CharField(max_length=5)),
                ('previsao_final', models.CharField(max_length=5)),
            ],
        ),
    ]
